[package]
name = "nexa-crypto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nexa-common = { path = "../nexa-common" }
x25519-dalek.workspace = true
ed25519-dalek.workspace = true
chacha20poly1305.workspace = true
hkdf.workspace = true
sha2.workspace = true
rand.workspace = true
rand_core.workspace = true
thiserror.workspace = true
bytes.workspace = true
serde = { workspace = true, features = ["derive"] }
hex = "0.4"
